import { Tree } from "./tree.mjs";
const arr = [1, 2, 3, 4, 5, 6, 7];
const tree = new Tree();
tree.setRoot(arr);
tree.insert(8);
tree.insert(5);
//tree.deleteItem(8, tree.root);
//tree.deleteItem(4, tree.root);
//tree.deleteItem(5, tree.root);
//tree.deleteItem(4, tree.root);
//console.log(tree.getRoot());
tree.prettyPrint(tree.getRoot());
tree.recuresionBreadthFirt((e) => console.log(e.data));
